
<div class="nested-data-type_entity_label"> <?= $label ?> </div>
<input type="hidden" class="nested-data-type_value" data-value-key="@value"/>

<div class="nested-data-type_properties">
    <div class="nested-data-type_repeat_property">
        <input class="nested-data-type_property_dropdown" list="property-dropdown" data-value-key="property-label-1" placeholder="Select a property">
        <datalist id="property-dropdown" name="property-dropdown">
            <?php foreach($properties as $property): ?>
                <option value="<?= $property->label() ?>"><?= $property->term() ?></option>
            <?php endforeach; ?>
        </datalist>
        <textarea name="property-value" data-value-key="property-value-1"></textarea>
        <button class="nested-data-type_button o-icon-delete nested-data-type_remove_property"></button>
    </div>
</div>

<button class="nested-data-type_button  o-icon-add nested-data-type_add_property">Add Property</button>