
<div class="nested-data-type_entity_label"> <?= $label ?> </div>
<input type="hidden" class="nested-data-type_value" data-value-key="@value" />
<div class="nested-data-type_properties" data-value-key="@id">
    <div class="nested-data-type_repeat_property">
        <select name="property-dropdown" data-value-key="property-label-1">
            <?php foreach($properties as $property): ?>
                <option value="<?= $property->term() ?>"><?= $property->label() ?></option>
            <?php endforeach; ?>
        </select>
        <textarea name="property-value" data-value-key="property-value-1"></textarea>
    </div>
</div>

<label class="o-icon-add nested-data-type_add_property">Add Property</label>