<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$itemsFound = count($items) > 0;
$expanded = $resourceClassId || $itemSetId || $id;
?>

<div id="item-results">
    <h3><?php echo $translate('Select item'); ?></h3>

    <div class="search-nav">
        <div id="sidebar-resource-search" class="resource-search" data-search-url="<?php echo $escape($this->url(null, [], [], true)); ?>">
            <?php
            echo $this->queryToHiddenInputs([
                'sort_by', 'sort_order', 'page',
                'search', 'resource_class_id', 'item_set_id', 'id',
            ]);
            ?>
            <input type="text" name="search" id="resource-list-search" value="<?php echo $escape($search); ?>">
            <button type="button" class="o-icon-search"><?php echo $translate('Search'); ?></button>
            
        </div>
        <?php if ($itemsFound): ?>
        <?php echo $this->pagination('common/sidebar-pagination.phtml'); ?>
        <?php endif; ?>
    </div>

    <?php if ($itemsFound): ?>

    <div class="items resource-list">
        <?php foreach ($items as $item):?>
        <div class="resource item" data-resource-values="<?php echo $escape(json_encode($item->valueRepresentation())); ?>">
            <?php
            $content = sprintf(
                '%s<span class="resource-name">%s</span>',
                $this->thumbnail($item, 'square'),
                $escape($item->displayTitle())
            );
            $attrs = [
                'class' => 'select-resource resource-link nested-data-type__resource_link',
            ];
            echo $hyperlink->raw($content, '#', $attrs);
            ?>
        </div>
        <?php endforeach; ?>
    </div>
    <?php else: ?>
    <span class="no-resources"><?php echo $translate(sprintf('No %s found.', $translate('items'))); ?></span>
    <?php endif; ?>
</div>
