<div class="nested-data-type_entity_label"> <?= $label ?> </div>
<input type="hidden" class="nested-data-type_value" data-value-key="@value" />

<div class="nested-data-type_properties">
    <datalist id="property-dropdown" name="property-dropdown">
        <?php foreach ($properties as $property) : ?>
            <option value="<?= $property->term() ?>"><?= $property->label() ?></option>
        <?php endforeach; ?>
    </datalist>
    <datalist id="class-dropdown" name="class-dropdown">
        <?php foreach ($classes as $class) : ?>
            <option value="<?= $class->term() ?>"><?= $class->label() ?></option>
        <?php endforeach; ?>
    </datalist>
    <div class="nested-data-type_repeat_property">
        <div class="nested-data-type_repeat_property_list">
            <div class="nested-data-type_handle"></div>
            <input class="nested-data-type-dropwdown nested-data-type_property_dropdown" list="property-dropdown" data-value-key="property-label-1" placeholder="Select a property" />
            <button class="nested-data-type_button o-icon-add nested-data-type_add_class"></button>
        </div>
        <div class="nested-data-type_repeat_class hidden">
            <input class="nested-data-type-dropwdown inner-class" list="class-dropdown" data-value-key="inner-class-1" placeholder="Select a class" />
            <input class="nested-data-type-dropwdown inner-property" list="property-dropdown" data-value-key="inner-property-1" placeholder="Select a property" />
        </div>
        <div class="input">
            <label class="value">
                <textarea class="property-value" name="property-value" data-value-key="property-value-1"></textarea>
            </label>
        </div>
        <div class="input hidden">
            <label class="value-uri">
                <textarea class="property-uri" name="property-uri" data-value-key="property-uri-1"></textarea>
            </label>
        </div>
        <input type="hidden" class="nested-data-type_is-hidden" data-value-key="is-hidden-1" />
        <button class="nested-data-type_button o-icon-public nested-data-type_hide_property"></button>
        <button class="nested-data-type_button o-icon-delete nested-data-type_remove_property"></button>
    </div>
</div>

<button class="nested-data-type_button o-icon-add nested-data-type_add_property">Add Property</button>

<a class="nested-data-type_button nested-data-type_add_resource o-icon- fa-link button resource-select" data-sidebar-content-url="<?= $this->url('admin/default', ['controller' => 'nested-data-type', 'action' => 'sidebar-select'], false) ?>" href="#item-resource-select">
    Link Item
</a>